[package]
name = "emoji-stat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
counter = "0.5.7"
emojis = "0.6.1"
unicode-segmentation = "1.11.0"
